################################################################################
# Neural Network
input_dim: 58
hidden_1_dim: 32
hidden_2_dim: 16
hidden_3_dim: 16
output_dim: 1

# relu | leaky_relu | gelu | tanh
hidden_activation: relu

# none | sigmoid | tanh
# Use "none" (linear) if data is standardized (recommended default).
# Use "sigmoid" only if your raw inputs are scaled to [0, 1] and standardize=false.
output_activation: none

################################################################################
# Tree
max_depth: 8
min_samples_split: 8
min_samples_leaf: 8

################################################################################
# Random Forest
n_estimators: 100
max_features: 8
n_jobs: -1

################################################################################
# Gaussian Process
constant_value: 1.0
constant_bounds: [1e-3, 1e3]

length_scale: 1.0
length_scale_bounds: [5e-1, 1e2]

noise_level: 1.0
noise_level_bounds: [1e-1, 1e1]

n_restarts_optimizer: 10

################################################################################
# Response Surface Method

degree: 2
interaction_only: false
alpha: 1.0   
